version: '3'

services:
    coding-challenge-devops:
        container_name: coding-challenge-devops
        image: ${REACT_APP_NODE_PORT}
        restart: on-failure
        build:
            context: .
            dockerfile: Docker/node/dockerfile
        ports:
            - ${REACT_APP_NODE_PORT}
        volumes:
            - '.:/app'
            - '/app/node_modules'
        environment:
            - NODE_ENV=development

    e2e:
        image: cypress
        build:
            # context: .
            dockerfile: Docker/cypress/dockerfile
        container_name: cypress
        depends_on:
            - coding-challenge-devops
        volumes:
            - ./cypress:/app/cypress
            - ./cypress.config.js:/app/cypress.config.js

    # # this container will run Cypress test using built-in Electron browser
    # e2e-electron:
    #     image: 'cypress/included:4.1.0'
    #     volumes:
    #         - ./cypress:/cypress
    #         - ./cypress.config.js:/cypress.config.js

    # # this container will run Cypress test using Chrome browser
    # e2e-chrome:
    #     image: 'cypress/included:4.1.0'
    #     command: '--browser chrome'
    #     volumes:
    #         - ./cypress:/cypress
    #         - ./cypress.config.js:/cypress.config.js

    # # this container will run Cypress test using Firefox browser
    # e2e-firefox:
    #     image: 'cypress/included:4.1.0'
    #     command: '--browser firefox --config video=false'
    #     environment:
    #         - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    #     volumes:
    #         - ./cypress:/cypress
    #         - ./cypress.config.js:/cypress.config.js
